"""The profile: what twinpc knows about the two machines (~/.config/twinpc/profile.toml).

`detect` writes it from the probe output of both machines; the user may edit it. When a profile
already exists, detected values only fill in missing keys unless force=True; [user] keys are never
overwritten. A shell-sourceable profile.env is written next to it for the `twin` command and hook.
"""
import os
import re
import shlex
import tomllib
from pathlib import Path

VERSION = 1
MACHINE_KEYS = ["family", "pkg", "desktop", "session", "gpu", "gpu_arch", "luks", "initramfs",
                "bootloader", "wired_iface", "wired_mac", "wol", "addr"]
CABLE_MAIN_ADDR = "10.42.0.1"          # NetworkManager "Shared to other computers" address
SECTIONS = ("network", "main", "twin", "user")


class ProfileError(Exception):
    pass


# values that end up in shell commands, ssh arguments and unit files must match these (empty is allowed)
_IFACE = r"[A-Za-z0-9_.:-]{1,15}"
_IPV4 = r"(25[0-5]|2[0-4]\d|1?\d?\d)(\.(25[0-5]|2[0-4]\d|1?\d?\d)){3}"
_MAC = r"([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}"
PATTERNS = {
    ("network", "twin_host"): r"[A-Za-z0-9][A-Za-z0-9._@-]*",
    ("network", "twin_addr"): _IPV4,
    ("network", "main_iface"): _IFACE,
    ("user", "twin_user"): r"[a-z_][a-z0-9_-]*\$?",
    ("user", "twin_mac"): _MAC,
    ("user", "twin_side"): r"left|right|top|bottom",
    **{(m, "wired_iface"): _IFACE for m in ("main", "twin")},
    **{(m, "wired_mac"): _MAC for m in ("main", "twin")},
    **{(m, "addr"): _IPV4 for m in ("main", "twin")},
}


def validate(profile):
    for (section, key), pattern in PATTERNS.items():
        value = profile.get(section, {}).get(key, "")
        if value != "" and not re.fullmatch(pattern, str(value)):
            raise ProfileError(f"[{section}] {key} = {value!r} is not a valid value — fix it in the profile")
    return profile


def config_dir():
    return Path(os.environ.get("XDG_CONFIG_HOME") or Path.home() / ".config") / "twinpc"


def profile_path():
    return config_dir() / "profile.toml"


def parse_probe(text):
    out = {}
    for line in text.splitlines():
        key, sep, value = line.partition("=")
        if sep and key.strip():
            out[key.strip()] = value.strip()
    return out


def _machine(probe):
    m = {k: probe.get(k, "") for k in MACHINE_KEYS}
    m["luks"] = probe.get("luks") == "true"
    return m


def build(main_probe, twin_probe, existing=None, force=False, twin_host="twin"):
    fresh = {
        "version": VERSION,
        "network": {
            "twin_host": twin_host,
            "mode": "cable" if main_probe.get("addr") == CABLE_MAIN_ADDR else "lan",
            "main_iface": main_probe.get("wired_iface", ""),
        },
        "main": _machine(main_probe),
        "twin": _machine(twin_probe) if twin_probe else {},
        "user": {},
    }
    if twin_probe:
        fresh["network"]["twin_addr"] = twin_probe.get("addr", "")
        fresh["user"] = {"twin_user": twin_probe.get("user", ""), "twin_mac": twin_probe.get("wired_mac", "")}
    if not existing:
        return fresh
    merged = {"version": VERSION}
    for section in SECTIONS:
        old, new = existing.get(section, {}), fresh.get(section, {})
        if section == "user" or not force:
            merged[section] = {**new, **old}     # existing values win; only missing keys are filled
        else:
            merged[section] = {**old, **new}     # --force: detected values win
    return merged


def _toml_value(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    s = str(v).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{s}"'


def dumps(profile):
    lines = ["# written by `twinpc detect` — edit freely; detect only fills in missing values",
             f"version = {profile.get('version', VERSION)}", ""]
    for section in SECTIONS:
        lines.append(f"[{section}]")
        for key, value in profile.get(section, {}).items():
            lines.append(f"{key} = {_toml_value(value)}")
        lines.append("")
    return "\n".join(lines)


def to_env(profile):
    n, u = profile.get("network", {}), profile.get("user", {})
    values = {"TWIN_HOST": n.get("twin_host", ""), "TWIN_ADDR": n.get("twin_addr", ""),
              "TWIN_IFACE": n.get("main_iface", ""), "TWIN_USER": u.get("twin_user", ""),
              "TWIN_MAC": u.get("twin_mac", "")}
    lines = ["# generated by `twinpc detect` from profile.toml — do not edit; environment variables win"]
    lines += [f"{k}=${{{k}:-{shlex.quote(v)}}}" for k, v in values.items() if v]
    return "\n".join(lines) + "\n"


def save(profile, path=None):
    validate(profile)
    path = Path(path or profile_path())
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(dumps(profile))
    path.with_name("profile.env").write_text(to_env(profile))
    return path


def load(path=None):
    path = Path(path or profile_path())
    if not path.exists():
        raise ProfileError(f"no profile at {path} — run: twinpc detect")
    with open(path, "rb") as f:
        profile = tomllib.load(f)
    if profile.get("version", 0) > VERSION:
        raise ProfileError(f"profile version {profile['version']} is newer than this twinpc ({VERSION}) — upgrade twinpc")
    return validate(profile)
